#!/bin/sh

# I need to install rlwrap on Windows - but not for now.
# rlwrap java -cp cljs.jar:src clojure.main node_repl.clj
cmd //c /c/cygwin64/home/ljones/.lein/bin/lein.bat trampoline run -m clojure.main scripts/node_repl.clj
