#!/bin/sh

# I need to install rlwrap on Windows - but not for now.
# rlwrap lein trampoline run -m clojure.main scripts/node.clj
cmd //c /c/cygwin64/home/ljones/.lein/bin/lein.bat trampoline run -m clojure.main scripts/node.clj
